# Generated by Django 4.0.1 on 2022-01-27 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('author', models.CharField(choices=[('jk rowling', 'JK Rowling'), ('dan brown', 'Dan Brown'), ('suzanne collins', 'Suzanne Collins'), ('john green', 'John Green'), ('veronica roth', 'Veronica Roth'), ('nicholas sparks', 'Nicholas Sparks')], max_length=255)),
                ('book_name', models.CharField(choices=[('harry potter series', 'Harry Potter Series'), ('angels and demons', 'Angels and Demons'), ('the hunger games', 'The Hunger Games'), ('turtles all the way down', 'Turtles All the Way Down'), ('divergent', 'Divergent'), ('a walk to remember', 'A Walk to Remember')], max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='count',
        ),
    ]
