# Generated by Django 4.0.1 on 2022-01-27 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_foodchainstore_guitarstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('brand_name', models.CharField(choices=[('h&m', 'H&M'), ('uniqlo', 'Uniqlo'), ('gap', 'Gap'), ('levis', 'Levis'), ('white_off', 'White_Off')], max_length=255)),
                ('type_of_clothes', models.CharField(choices=[('t-shirt', 'T-Shirt'), ('pants', 'Pants'), ('jackets', 'Jackets'), ('blouse', 'Blouse')], max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='SneakersStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('brand_name', models.CharField(choices=[('adidas', 'Adidas'), ('nike', 'Nike'), ('reebok', 'Reebok'), ('converse', 'Converse'), ('vans', 'Vans'), ('puma', 'Puma')], max_length=255)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
