# Generated by Django 4.0.1 on 2022-01-27 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_clothingstore_sneakersstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('artist_name', models.CharField(choices=[('leonardo da vinci', 'Leonardo da Vinci'), ('vincent van gogh', 'Vincent Van Gogh'), ('johannes vermeer', 'Johannes Vermeer'), ('pablo picasso', 'Pablo Picasso'), ('gustav klimt', 'Gustav Klimt'), ('edvard munch', 'Edvard Munch')], max_length=255)),
                ('art_title', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='CarStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('brand_name', models.CharField(choices=[('audi', 'Audi'), ('bmw', 'BMW'), ('bentley', 'Bentley'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('porsche', 'Porsche')], max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='MusicStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('singer_name', models.CharField(choices=[('keshi', 'keshi'), ('lullaboy', 'lullaboy'), ('bruno major', 'Bruno Major'), ('dhruv', 'dhruv'), ('bruno mars', 'Bruno Mars'), ('post malone', 'Post Malone')], max_length=255)),
                ('album_title', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
